version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
      time: '23:00'
      timezone: Europe/London
    cooldown:
      semver-major: 12
      semver-minor: 8
      semver-patch: 4
    open-pull-requests-limit: 5
    # ignore:
    #   - dependency-name: "*"
    #     update-types: ["version-update:semver-major"]
